site_name: Pheasant
site_url: https://pheasant.daizutabi.net/
site_description: Project documentation with MkDocs.
site_author: daizutabi

repo_url: https://github.com/daizutabi/pheasant/
edit_uri: ""

theme: readthedocs

plugins:
  - pheasant:
      version: pheasant
nav:
  - Home: index.md
  - Main: main.md
  - Test: test.md
  - Script: conftest.py
  - Section: section
  - section
